# Generated by Django 5.2.11 on 2026-04-23 00:39

import django.db.models.deletion
import session.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=10)),
                ('trigger_type', models.CharField(choices=[('points', 'Points Threshold'), ('streak', 'Streak Threshold'), ('activity', 'Activity Completion'), ('count', 'Answer Count')], max_length=10)),
                ('trigger_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=session.models.generate_session_code, max_length=6, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('facilitator_name', models.CharField(max_length=100)),
                ('facilitator_password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('ended', 'Ended')], default='waiting', max_length=10)),
                ('current_slide_index', models.PositiveIntegerField(default=0)),
                ('activity_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.CharField(default='🌱', max_length=10)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('max_streak', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('badges', models.ManyToManyField(blank=True, to='session.badge')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='session.session')),
            ],
            options={
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slide_type', models.CharField(choices=[('info', 'Information'), ('activity', 'Activity')], default='info', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('activity_type', models.CharField(blank=True, choices=[('poll', 'Poll'), ('sort', 'Sort'), ('guess', 'Guess Timeline'), ('discuss', 'Discussion Wall'), ('commit', 'Commitment Wall'), ('match', 'Definition Match'), ('problem', 'Problem Identification'), ('case_study', 'Case Study / Transfer Station')], max_length=15, null=True)),
                ('activity_config', models.JSONField(blank=True, null=True)),
                ('shocking_fact', models.BooleanField(default=False)),
                ('time_hint', models.PositiveIntegerField(blank=True, help_text='Seconds to display', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='session.session')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnonymousPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='session.session')),
                ('slide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='session.slide')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=15)),
                ('answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='session.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='session.session')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='session.slide')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
