# Generated by Django 5.2.11 on 2026-04-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='facilitator_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='facilitator_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
