# Generated by Django 5.2.11 on 2026-04-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_facilitator_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('sprint', '♻️ Waste Sorting Sprint'), ('decompose', '⏳ Decomposition Race'), ('quiz', '🌍 Plastic vs Planet Quiz'), ('commitment', '💚 Green Commitment'), ('sort_stats', '📊 Sort the Stats')], max_length=15, null=True),
        ),
    ]
