# Generated by Django 5.2.11 on 2026-04-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_activity_template_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
