# Generated by Django 5.2.11 on 2026-04-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_add_phone_to_participant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('name', 'trigger_type', 'trigger_value')},
        ),
        migrations.AddIndex(
            model_name='activityresult',
            index=models.Index(fields=['session', 'slide'], name='session_act_session_684edd_idx'),
        ),
        migrations.AddIndex(
            model_name='activityresult',
            index=models.Index(fields=['session', '-submitted_at'], name='session_act_session_e6ad37_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymouspost',
            index=models.Index(fields=['session', 'slide', 'is_public', '-created_at'], name='session_ano_session_690417_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['session', '-total_points'], name='session_par_session_c8d76d_idx'),
        ),
    ]
