# Generated by Django 5.2.11 on 2026-04-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_alter_badge_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='show_answers_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
